version: '3'
services:
  lb:
    image: haproxy:1.8
    ports:
      - "5000:5000"
      - "1936:1936"
    volumes:
      - ${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - db
      - pgbouncer

  db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dbuser
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=test

  pgbouncer:
    image: pgbouncer:dev
    environment:
       - DB_USER=dbuser
       - DB_PASSWORD=dbuser
       - DB_HOST=db
       - DB_NAME=test 
       - POOL_MODE=transaction
       - ADMIN_USERS=postgres,dbuser
    ports:
      - "6432:6432"
    depends_on:
      - db

volumes:
  pg_data:
